{% set name = "microsoft-kiota-authentication-azure" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_authentication_azure-{{ version }}.tar.gz
  sha256: 752304f8d94b884cfec12583dd763ec0478805c7f80b29344e78c6d55a97bd01

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.8.0
    - azure-core >=1.21.1
    - microsoft-kiota-abstractions >=1.0.0,<2.0.0
    - opentelemetry-api >=1.20.0
    - opentelemetry-sdk >=1.20.0

test:
  imports:
    - kiota_authentication_azure
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/kiota-authentication-azure-python
  summary: Authentication provider for Kiota using Azure Identity
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/kiota-authentication-azure-python
  doc_url: https://github.com/microsoft/kiota-authentication-azure-python/blob/main/README.md

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/48409
    reason: Dependenccy for msgraph-sdk
    recipe-maintainers:
      - ianaobi
  recipe-maintainers:
    - xylar
